-- Copy this ENTIRE file into Supabase SQL Editor and click Run.
-- First line must start with two dashes: --

-- Contact form messages
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  email text not null,
  message text not null,
  source text
);

alter table public.contact_messages enable row level security;

drop policy if exists "Allow public contact submissions" on public.contact_messages;
create policy "Allow public contact submissions"
on public.contact_messages
for insert
to anon
with check (
  length(email) > 3
  and length(message) > 0
);

grant insert on table public.contact_messages to anon;

-- Waitlist, VIP, newsletter, sponsor
create table if not exists public.waitlist_subscriptions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  message text,
  source_path text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  constraint waitlist_subscriptions_email_key unique (email),
  constraint waitlist_subscriptions_status_check check (status in ('active', 'unsubscribed'))
);

alter table public.waitlist_subscriptions
add column if not exists message text;

create table if not exists public.vip_subscription_requests (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  message text,
  source_path text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  constraint vip_subscription_requests_email_key unique (email),
  constraint vip_subscription_requests_status_check check (status in ('active', 'contacted', 'converted', 'declined'))
);

create table if not exists public.newsletter_subscriptions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  message text,
  source_path text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  constraint newsletter_subscriptions_email_key unique (email),
  constraint newsletter_subscriptions_status_check check (status in ('active', 'unsubscribed'))
);

create table if not exists public.sponsor_inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  message text,
  source_path text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  constraint sponsor_inquiries_email_key unique (email),
  constraint sponsor_inquiries_status_check check (status in ('active', 'contacted', 'closed'))
);

alter table public.waitlist_subscriptions enable row level security;
alter table public.vip_subscription_requests enable row level security;
alter table public.newsletter_subscriptions enable row level security;
alter table public.sponsor_inquiries enable row level security;

grant insert on table public.waitlist_subscriptions to anon;
grant insert on table public.vip_subscription_requests to anon;
grant insert on table public.newsletter_subscriptions to anon;
grant insert on table public.sponsor_inquiries to anon;

drop policy if exists "Allow public waitlist signups" on public.waitlist_subscriptions;
create policy "Allow public waitlist signups"
on public.waitlist_subscriptions
for insert
to anon
with check (
  status = 'active'
  and length(trim(name)) > 1
  and email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
);

drop policy if exists "Allow public VIP signups" on public.vip_subscription_requests;
create policy "Allow public VIP signups"
on public.vip_subscription_requests
for insert
to anon
with check (
  status = 'active'
  and length(trim(name)) > 1
  and email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
);

drop policy if exists "Allow public newsletter signups" on public.newsletter_subscriptions;
create policy "Allow public newsletter signups"
on public.newsletter_subscriptions
for insert
to anon
with check (
  status = 'active'
  and length(trim(name)) > 1
  and email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
);

drop policy if exists "Allow public sponsor inquiries" on public.sponsor_inquiries;
create policy "Allow public sponsor inquiries"
on public.sponsor_inquiries
for insert
to anon
with check (
  status = 'active'
  and length(trim(name)) > 1
  and email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'
);
