/**
 * Generated by scripts/sync-basic-physics-previews.mjs — do not edit by hand.
 */
export const BASIC_PHYSICS_PREVIEW_BASE = '/previews/basic-physics'

export const basicPhysicsPreviews = [
  {
    title: "Condensed Matter",
    file: "condensed-matter.pdf",
    sizeBytes: 64573869,
    sizeLabel: "61.6 MB"
  },
  {
    title: "Mechanics",
    file: "mechanics.pdf",
    sizeBytes: 44596836,
    sizeLabel: "42.5 MB"
  },
  {
    title: "Quantum Field Theory",
    file: "quantum-field-theory.pdf",
    sizeBytes: 26064991,
    sizeLabel: "24.9 MB"
  },
  {
    title: "Quantum Mechanics",
    file: "quantum-mechanics.pdf",
    sizeBytes: 20399398,
    sizeLabel: "19.5 MB"
  },
  {
    title: "Statistical Physics",
    file: "statistical-physics.pdf",
    sizeBytes: 37790944,
    sizeLabel: "36.0 MB"
  }
]
